package com.example.android.playground.annotationprocessing.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate

/**
 * KSP [SymbolProcessor] that generates a `toJson()` extension for classes annotated with [AutoJson].
 */
class AutoJsonProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotationName =
            AutoJson::class.qualifiedName
                ?: error("Could not resolve AutoJson qualified name")

        val symbols = resolver.getSymbolsWithAnnotation(annotationName)
        val (valid, deferred) = symbols.partition { it.validate() }

        valid
            .filterIsInstance<KSClassDeclaration>()
            .forEach { classDeclaration ->
                logger.info(
                    "AutoJsonProcessor -> generating for ${classDeclaration.qualifiedName?.asString()}",
                )
                generateExtension(classDeclaration)
            }

        return deferred.toList()
    }

    private fun generateExtension(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()

        val properties =
            classDecl
                .getAllProperties()
                .filter { it.hasBackingField }
                .map { property ->
                    val typeName =
                        property.type
                            .resolve()
                            .declaration.simpleName
                            .asString()
                    JsonProperty(
                        name = property.simpleName.asString(),
                        quoteValue = typeName == "String",
                    )
                }.toList()

        val outputStream =
            codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = false, classDecl.containingFile!!),
                packageName = packageName,
                fileName = "${className}ToJson",
            )

        val dollar = "\$"
        val jsonParts =
            properties.joinToString(",") { prop ->
                if (prop.quoteValue) {
                    "\\\"${prop.name}\\\":\\\"${dollar}${prop.name}\\\""
                } else {
                    "\\\"${prop.name}\\\":${dollar}${prop.name}"
                }
            }

        val content =
            buildString {
                appendLine("package $packageName")
                appendLine()
                appendLine("// AUTO-GENERATED by AutoJsonProcessor - do not edit")
                appendLine()
                if (properties.isEmpty()) {
                    appendLine("fun $className.toJson(): String = \"{}\"")
                } else {
                    appendLine("fun $className.toJson(): String = \"{$jsonParts}\"")
                }
            }

        outputStream.bufferedWriter().use { it.write(content) }
    }

    private data class JsonProperty(
        val name: String,
        val quoteValue: Boolean,
    )
}
