package com.example.android.playground.annotationprocessing.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate

/**
 * KSP [SymbolProcessor] that generates a `generatedToString()` extension function for every
 * class annotated with [AutoToString].
 *
 * For a class `Foo(val a: Int, val b: String)` the processor writes:
 * ```kotlin
 * fun Foo.generatedToString(): String = "Foo(a=$a, b=$b)"
 * ```
 * into `<packageName>/FooGeneratedToString.kt` under the KSP-generated sources directory.
 *
 * **Pipeline summary**:
 * 1. `process()` is called by the KSP runtime during the compilation phase.
 * 2. `Resolver.getSymbolsWithAnnotation()` locates annotated symbols.
 * 3. Invalid (deferred) symbols are returned for a later processing round.
 * 4. `CodeGenerator.createNewFile()` writes the generated Kotlin source.
 */
class AutoToStringProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotationName =
            AutoToString::class.qualifiedName
                ?: error("Could not resolve AutoToString qualified name")

        val symbols = resolver.getSymbolsWithAnnotation(annotationName)
        val (valid, deferred) = symbols.partition { it.validate() }

        valid
            .filterIsInstance<KSClassDeclaration>()
            .forEach { classDeclaration ->
                logger.info(
                    "AutoToStringProcessor → generating for ${classDeclaration.qualifiedName?.asString()}",
                )
                generateExtension(classDeclaration)
            }

        // Return deferred symbols so KSP can retry them in the next processing round
        return deferred.toList()
    }

    private fun generateExtension(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()

        // Collect properties that have a backing field (i.e. constructor val/var params)
        val properties =
            classDecl
                .getAllProperties()
                .filter { it.hasBackingField }
                .map { it.simpleName.asString() }
                .toList()

        val outputStream =
            codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = false, classDecl.containingFile!!),
                packageName = packageName,
                fileName = "${className}GeneratedToString",
            )

        outputStream.bufferedWriter().use { writer ->
            writer.write("package $packageName\n")
            writer.write("\n")
            writer.write("// AUTO-GENERATED by AutoToStringProcessor — do not edit\n")
            writer.write("\n")
            writer.write("fun $className.generatedToString(): String {\n")
            if (properties.isEmpty()) {
                writer.write("    return \"$className()\"\n")
            } else {
                val parts = properties.joinToString(", ") { name -> "$name=\$$name" }
                writer.write("    return \"$className($parts)\"\n")
            }
            writer.write("}\n")
        }
    }
}
