package com.example.android.playground.annotationprocessing.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.validate

/**
 * KSP [SymbolProcessor] that generates a `validate()` extension for classes annotated with [Validate].
 */
class ValidateProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotationName =
            Validate::class.qualifiedName
                ?: error("Could not resolve Validate qualified name")

        val symbols = resolver.getSymbolsWithAnnotation(annotationName)
        val (valid, deferred) = symbols.partition { it.validate() }

        valid
            .filterIsInstance<KSClassDeclaration>()
            .forEach { classDeclaration ->
                logger.info(
                    "ValidateProcessor -> generating for ${classDeclaration.qualifiedName?.asString()}",
                )
                generateExtension(classDeclaration)
            }

        return deferred.toList()
    }

    private fun generateExtension(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()

        val rules =
            classDecl
                .getAllProperties()
                .filter { it.hasBackingField }
                .flatMap { property -> buildRules(property) }

        val outputStream =
            codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = false, classDecl.containingFile!!),
                packageName = packageName,
                fileName = "${className}Validate",
            )

        val content =
            buildString {
                appendLine("package $packageName")
                appendLine()
                appendLine("// AUTO-GENERATED by ValidateProcessor - do not edit")
                appendLine()
                appendLine("fun $className.validate(): List<String> {")
                appendLine("    val errors = mutableListOf<String>()")
                rules.forEach { rule ->
                    when (rule) {
                        is ValidationRule.NotBlankRule -> {
                            appendLine("    if (${rule.propertyName}.isBlank()) {")
                            appendLine("        errors.add(\"${rule.propertyName} must not be blank\")")
                            appendLine("    }")
                        }

                        is ValidationRule.MinValueRule -> {
                            appendLine("    if (${rule.propertyName} < ${rule.minValue}) {")
                            appendLine("        errors.add(\"${rule.propertyName} must be >= ${rule.minValue}\")")
                            appendLine("    }")
                        }
                    }
                }
                appendLine("    return errors")
                append("}")
            }

        outputStream.bufferedWriter().use { it.write(content) }
    }

    private fun buildRules(property: KSPropertyDeclaration): List<ValidationRule> {
        val propertyName = property.simpleName.asString()
        val rules = mutableListOf<ValidationRule>()

        property.annotations.forEach { annotation ->
            when (annotation.shortName.asString()) {
                NotBlank::class.simpleName -> {
                    rules += ValidationRule.NotBlankRule(propertyName = propertyName)
                }

                MinValue::class.simpleName -> {
                    val minValue = (annotation.arguments.firstOrNull()?.value as? Int) ?: return@forEach
                    rules += ValidationRule.MinValueRule(propertyName = propertyName, minValue = minValue)
                }
            }
        }

        return rules
    }

    private sealed interface ValidationRule {
        data class NotBlankRule(
            val propertyName: String,
        ) : ValidationRule

        data class MinValueRule(
            val propertyName: String,
            val minValue: Int,
        ) : ValidationRule
    }
}
